/* readFromFileFrame.java
 * Created on 03-Feb-2014, 20:57:56 By Will Hogan
 * Object Oriented Programming Assignment 1, Retail Payroll System.
 */

package Payroll;

public class readFromFileFrame extends javax.swing.JFrame {

    /** Creates new form readFromFileFrame */
    public readFromFileFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PaySlipPrintOutScrollPane = new javax.swing.JScrollPane();
        PaySlipPrintOutTextArea = new javax.swing.JTextArea();
        PaySlipPrintOutLabel = new javax.swing.JLabel();
        mainMenuButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        payrollMenuBar = new javax.swing.JMenuBar();
        payrollMenuBarLine = new javax.swing.JMenu();
        toPrinterMenuItem = new javax.swing.JMenuItem();
        payrollSeparator = new javax.swing.JSeparator();
        exitMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PaySlip Print Out Frame");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        PaySlipPrintOutTextArea.setColumns(20);
        PaySlipPrintOutTextArea.setRows(5);
        PaySlipPrintOutScrollPane.setViewportView(PaySlipPrintOutTextArea);

        PaySlipPrintOutLabel.setFont(new java.awt.Font("Tahoma", 1, 24));
        PaySlipPrintOutLabel.setForeground(new java.awt.Color(0, 0, 153));
        PaySlipPrintOutLabel.setText(" Payslip Print Out");
        PaySlipPrintOutLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        mainMenuButton.setFont(new java.awt.Font("Tahoma", 1, 18));
        mainMenuButton.setForeground(new java.awt.Color(0, 0, 153));
        mainMenuButton.setText("Main Menu");
        mainMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMenuButtonActionPerformed(evt);
            }
        });

        closeButton.setFont(new java.awt.Font("Tahoma", 1, 18));
        closeButton.setForeground(new java.awt.Color(0, 0, 153));
        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        payrollMenuBarLine.setText("File");

        toPrinterMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        toPrinterMenuItem.setText("To Printer");
        payrollMenuBarLine.add(toPrinterMenuItem);
        payrollMenuBarLine.add(payrollSeparator);

        exitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        payrollMenuBarLine.add(exitMenuItem);

        payrollMenuBar.add(payrollMenuBarLine);

        setJMenuBar(payrollMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(PaySlipPrintOutScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(mainMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                        .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(PaySlipPrintOutLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {closeButton, mainMenuButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PaySlipPrintOutLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PaySlipPrintOutScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(closeButton, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                    .addComponent(mainMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {closeButton, mainMenuButton});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mainMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenuButtonActionPerformed
        // Launches the Main Menu
        MenuFrame frame = new MenuFrame();
        frame.setVisible(true);
        dispose();
}//GEN-LAST:event_mainMenuButtonActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        // Closes the Frame
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // Textarea is set to read only
        PaySlipPrintOutTextArea.setEditable(false);
    }//GEN-LAST:event_formWindowOpened

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        // Another way of closing the Frame, in the File tab, top left. 
        setVisible(false);
        dispose();
    }//GEN-LAST:event_exitMenuItemActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new readFromFileFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PaySlipPrintOutLabel;
    private javax.swing.JScrollPane PaySlipPrintOutScrollPane;
    public static javax.swing.JTextArea PaySlipPrintOutTextArea;
    private javax.swing.JButton closeButton;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JButton mainMenuButton;
    private javax.swing.JMenuBar payrollMenuBar;
    private javax.swing.JMenu payrollMenuBarLine;
    private javax.swing.JSeparator payrollSeparator;
    private javax.swing.JMenuItem toPrinterMenuItem;
    // End of variables declaration//GEN-END:variables

}
